#!/usr/bin/env bash
set -euo pipefail

curl -sS https://api.elevenlabs.io/v1/text-to-speech/onwK4e9ZLuTAKqWW03F9/stream -H 'Content-Type: application/json' -H 'Accept: audio/mpeg' -H 'xi-api-key: $ELEVENLABS_API_KEY' -d @<(jq -n --rawfile text /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/01_beginner_mistake.txt '{text:$text,model_id:"eleven_multilingual_v2",voice_settings:{stability:0.42,similarity_boost:0.82,style:0.18,use_speaker_boost:true}}') > /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/01_beginner_mistake.mp3
ffmpeg -y -i /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/01_beginner_mistake.mp3 -af "highpass=f=80,lowpass=f=8500,acompressor=threshold=-18dB:ratio=2.5:attack=5:release=120:makeup=3,alimiter=limit=0.92" /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/01_beginner_mistake.wav
curl -sS https://api.elevenlabs.io/v1/text-to-speech/onwK4e9ZLuTAKqWW03F9/stream -H 'Content-Type: application/json' -H 'Accept: audio/mpeg' -H 'xi-api-key: $ELEVENLABS_API_KEY' -d @<(jq -n --rawfile text /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/02_brain_electricity.txt '{text:$text,model_id:"eleven_multilingual_v2",voice_settings:{stability:0.42,similarity_boost:0.82,style:0.18,use_speaker_boost:true}}') > /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/02_brain_electricity.mp3
ffmpeg -y -i /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/02_brain_electricity.mp3 -af "highpass=f=80,lowpass=f=8500,acompressor=threshold=-18dB:ratio=2.5:attack=5:release=120:makeup=3,alimiter=limit=0.92" /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/02_brain_electricity.wav
curl -sS https://api.elevenlabs.io/v1/text-to-speech/onwK4e9ZLuTAKqWW03F9/stream -H 'Content-Type: application/json' -H 'Accept: audio/mpeg' -H 'xi-api-key: $ELEVENLABS_API_KEY' -d @<(jq -n --rawfile text /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/03_no_phd.txt '{text:$text,model_id:"eleven_multilingual_v2",voice_settings:{stability:0.42,similarity_boost:0.82,style:0.18,use_speaker_boost:true}}') > /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/03_no_phd.mp3
ffmpeg -y -i /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/03_no_phd.mp3 -af "highpass=f=80,lowpass=f=8500,acompressor=threshold=-18dB:ratio=2.5:attack=5:release=120:makeup=3,alimiter=limit=0.92" /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/03_no_phd.wav

ffmpeg -y -f concat -safe 0 -i /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/concat_list.txt -af "highpass=f=80,lowpass=f=8500,acompressor=threshold=-18dB:ratio=2.5:attack=5:release=120:makeup=3,alimiter=limit=0.92" /Users/rafael/visualbcimedia/visualbci_video_pipeline/audio/final_narration.wav
